name: GitHub Metrics

on:
  # Updates automatically once per day
  schedule:
    - cron: "0 0 * * *"

  # Lets you run it manually
  workflow_dispatch:

  # Runs whenever this workflow is edited
  push:
    branches:
      - main

jobs:
  generate-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate GitHub profile metrics (left)
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-left.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: ${{ github.repository_owner }}
          base: header
          base_indepth: yes
          config_timezone: America/Los_Angeles
          plugin_isocalendar: yes
          plugin_languages: yes
          
      - name: Generate Github profile metrics (right)
        uses: lowlighter/metrics@latest
        with:
            filename: github-metrics-right.svg
            base: ""
            token: ${{ secrets.METRICS_TOKEN }}
            user: ${{ github.repository_owner }}
            plugin_topics: yes
            plugin_topics_mode: icons
            plugin_topics_limit: 16
            plugin_people: yes
            plugin_people_types: followers
            plugin_people_limit: 24
            
